---
- name: install - chef-server-core_{{ chef_server_version }}-1_amd64.deb
  when: ansible_distribution == 'Ubuntu'
  apt:
    # yamllint disable-line rule:line-length
    deb: https://packages.chef.io/files/stable/chef-server/{{ chef_server_version }}/{{ ansible_distribution | lower}}/{{ ansible_distribution_version }}/chef-server-core_{{ chef_server_version }}-1_amd64.deb
  register: chef_dk_install
